#!/usr/bin/env python3
# =============================================================================
# compass - the per-issue review dashboard
# =============================================================================
# The page a reviewer opens first. An issue directory answers "what files
# exist"; this answers the questions a reviewer actually has - what am I being
# asked to approve, what should I read, and what was deliberately left out.
#
# IT CARRIES NO RAW EVIDENCE. Command output and test runs are linked, never
# reproduced. A review page that reproduces its evidence stops being two screens
# and stops being read, which is the whole complaint this page answers.
#
# It is GENERATED, never hand-edited, and guarded for staleness. That guard is
# not decoration: this repository already generates docs/system-spec.md from
# issue records, and its currency check fired twice on 2026-08-23. A generated
# page nobody checks is trusted anyway, which is worse than no page.
#
# DEPENDENCY: PyYAML, bundled at cli/vendor/yaml/ and pinned in
# THIRD-PARTY-NOTICES.md. It is resolved by compass_pkg/__init__.py and is
# the only third-party code Compass ships; everything else is the Python 3
# standard library. This module reaches it through compass_pkg.core.
# =============================================================================
"""Rendering the per-issue review dashboard from the artifact registry."""
from __future__ import annotations

import os

from compass_pkg.check_results import NOTHING_TO_CHECK
from compass_pkg.core import (FOUND, CompassError, load_yaml, resolve_artifact,
                             resolve_task_dir, save_task)

# The line that says the page was generated, and the marker the currency check
# reads. Kept out of the rendered body's meaning so a reader is not asked to
# care about it.
GENERATED_NOTE = ("<!-- GENERATED by `compass issue dashboard` - do not edit. "
                  "Regenerate after any stage. -->")

_STATUS_ORDER = {"awaiting-approval": 0, "draft": 1, "approved": 2,
                 "superseded": 3, "omitted": 4}


def _spine(task_dir):
    path = os.path.join(task_dir, "task.yml")
    try:
        task = load_yaml(path)
    except CompassError:
        return {}
    return task if isinstance(task, dict) else {}


def _artifacts(task):
    arts = task.get("artifacts")
    return [a for a in arts if isinstance(a, dict)] if isinstance(arts, list) else []


def _decision_line(task, pack):
    """What the reviewer is being asked, in one sentence.

    Taken from the artifact that is awaiting approval. When nothing awaits one,
    the page says so rather than inventing a decision - "no decision required"
    is a real answer and a reviewer needs it as much as any other.
    """
    waiting = [a for a in pack if a.get("status") == "awaiting-approval"]
    if not waiting:
        return None, "No decision required. Nothing is awaiting approval."
    first = waiting[0]
    return first, "Approve the %s - %s." % (first.get("kind", "document"),
                                            (first.get("reason") or "").rstrip("."))


def render_dashboard(task_dir):
    """The review page for one issue, as markdown."""
    task = _spine(task_dir)
    slug = task.get("task") or os.path.basename(os.path.abspath(task_dir))
    assessment = task.get("assessment") or {}
    pack = sorted(_artifacts(task),
                  key=lambda a: _STATUS_ORDER.get(a.get("status"), 9))
    present = [a for a in pack if a.get("status") != "omitted"]
    omitted = [a for a in pack if a.get("status") == "omitted"]
    waiting, decision = _decision_line(task, pack)

    out = [GENERATED_NOTE, "", "# %s" % slug, ""]

    approach = task.get("delivery_approach") or "not yet routed"
    bits = [str(approach)]
    if assessment.get("risk"):
        bits.append("%s risk" % assessment["risk"])
    if assessment.get("size"):
        bits.append("%s" % assessment["size"])
    out += ["**Status:** %s · **Approach:** %s" % (task.get("status", "?"),
                                                   " · ".join(bits)), ""]

    out += ["## Decision required", "", decision, ""]
    if waiting is not None and waiting.get("path"):
        out += ["**Read:** `%s`" % waiting["path"], ""]

    # The status column asks the RESOLVER, not just the registry. Routing seeds
    # every earned document as `draft` and nothing moves it, so a registry-only
    # column reported seven drafts for an issue that had written four documents
    # and never started three. A page that sends a reviewer looking for a file
    # that is not there is worse than no page - it is confidently wrong.
    out += ["## Review pack", ""]
    if present:
        out += ["| Document | Status | Why it exists |", "|---|---|---|"]
        for a in present:
            kind = a.get("kind", "?")
            state, _p, _why = resolve_artifact(task_dir, kind)
            # A registry status on a file that is not there means nothing, so
            # the disk wins. The resolver cannot tell "the entry names the
            # wrong path" from "nobody has written it yet" - on disk they are
            # the same absence - so both get the label that is true either way.
            status = a.get("status", "?") if state == FOUND else "not written yet"
            out.append("| %s | %s | %s |" % (
                kind, status, (a.get("reason") or "").replace("|", "-")))
    else:
        out.append("No documents registered yet.")
    out.append("")

    out += ["## Deliberately omitted", ""]
    if omitted:
        for a in omitted:
            out.append("- **%s** - %s" % (a.get("kind", "?"),
                                          (a.get("reason") or "no reason recorded")))
    else:
        out.append("Nothing recorded as omitted.")
    out.append("")

    # Evidence is LINKED. The registry entries are named and their paths given;
    # nothing is read out of the record files themselves.
    registry = [e for e in (task.get("evidence") or []) if isinstance(e, dict)]
    out += ["## Evidence", ""]
    if registry:
        out.append("Linked, not reproduced - open a record to read it.")
        out.append("")
        for e in registry:
            out.append("- `%s` (%s) - `%s`" % (e.get("id", "?"), e.get("type", "?"),
                                               e.get("path", "no path")))
    else:
        out.append("No evidence recorded yet.")
    out.append("")
    return "\n".join(out) + "\n"


def dashboard_is_current(task_dir):
    """Does the dashboard on disk match one rendered from the spine now?

    Returns (is_current, detail). A page that has drifted from its source is
    worse than no page, because it is still trusted.
    """
    path = os.path.join(task_dir, "README.md")
    if not os.path.isfile(path):
        return False, ("no README.md - regenerate it with "
                       "`compass issue dashboard`")
    with open(path, encoding="utf-8") as fh:
        on_disk = fh.read()
    if GENERATED_NOTE not in on_disk:
        # Someone hand-wrote it. Say so rather than overwriting silently.
        return False, ("README.md was not generated by Compass - it carries no "
                       "generated marker. Regenerate it with `compass issue "
                       "dashboard`, or move the hand-written page aside first")
    fresh = render_dashboard(task_dir)
    if on_disk.strip() != fresh.strip():
        return False, ("README.md no longer matches the issue spine - "
                       "regenerate it with `compass issue dashboard`")
    return True, "README.md matches the spine"


def _check_dashboard_current(task, task_dir):
    """The per-issue review page still matches the record it was generated from.

    Under G4, evidence-not-assertion: the dashboard states what documents exist,
    what is awaiting approval and what was left out. If the spine has moved
    since it was rendered, that page is an assertion the record contradicts -
    and it is the page a reviewer approves from, so nobody catches it.

    Two outcomes DECLINE rather than pass, and the distinction is the point.
    An issue with no dashboard is not being misled by one, and neither is a
    reader of a page a person wrote by hand. Reporting either as a pass would
    make this a check that clears without reading anything - which is exactly
    the failure this repository found four of in one release.
    """
    path = os.path.join(task_dir, "README.md")
    if not os.path.isfile(path):
        return NOTHING_TO_CHECK, ("no README.md on this issue - there is no "
                                  "generated review page to be out of date")
    with open(path, encoding="utf-8") as fh:
        if GENERATED_NOTE not in fh.read():
            return NOTHING_TO_CHECK, (
                "README.md carries no generated marker, so it is a page "
                "somebody wrote by hand - Compass does not judge it against "
                "the spine")

    current, detail = dashboard_is_current(task_dir)
    if not current:
        return False, (detail + " - run `compass issue dashboard` and re-read "
                       "it before approving anything from it")
    return True, detail

def cmd_issue_dashboard(args):
    """`compass issue dashboard` - render the review page, or check it is current.

    `--check` writes nothing and reports whether the page still matches the
    spine. That is the mode a currency guard calls: a generated page that has
    drifted is worse than no page, because it is still trusted.
    """
    from compass_pkg.core import resolve_task_dir

    task_dir = resolve_task_dir(getattr(args, "task", None))
    if getattr(args, "check", False):
        current, detail = dashboard_is_current(task_dir)
        print("compass issue dashboard: %s - %s"
              % ("current" if current else "STALE", detail))
        return 0 if current else 1

    page = render_dashboard(task_dir)
    path = os.path.join(task_dir, "README.md")
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(page)
    from compass_pkg.terminal import say

    return say(args, "compass issue dashboard: written -> %s" % path,
               detail=["%d line(s). Evidence is linked, not reproduced."
                       % len(page.splitlines())],
               path=path, lines=len(page.splitlines()))


# The statuses a document can be in. `draft` is what routing seeds; the rest
# are decisions a person makes, and until this verb existed none of them could
# be reached - which left the review page's two headline sections, "Decision
# required" and "Deliberately omitted", permanently empty.
ARTIFACT_STATUSES = ("draft", "awaiting-approval", "approved", "superseded",
                     "omitted")


def cmd_issue_artifact(args):
    """`compass issue artifact <kind> --status <s> [--reason ...]`.

    Refuses a kind the issue never earned, the way `tdd-red --scenario`
    refuses a scenario id that is not in the spine - a status set on a document
    nobody asked for is a typo that would otherwise be stored as a decision.

    An omission MUST carry a reason. Without one, a document deliberately
    dropped and a document nobody got to look the same on the page, and telling
    those apart is the reason the registry exists.
    """
    task_dir = resolve_task_dir(getattr(args, "task", None))
    path = os.path.join(task_dir, "task.yml")
    task = load_yaml(path)
    arts = [a for a in (task.get("artifacts") or []) if isinstance(a, dict)]

    entry = next((a for a in arts if a.get("kind") == args.kind), None)
    if entry is None:
        earned = ", ".join(sorted(a.get("kind", "?") for a in arts)) or "none"
        raise CompassError(
            "%r is not a document this issue earned (it earned: %s). The "
            "artifact set is computed from the assessment - re-run "
            "`compass approach evaluate --write`, or re-assess with "
            "`/compass:triage --reassess` if the work really changed shape."
            % (args.kind, earned))

    if args.status == "omitted" and not (args.reason or "").strip():
        raise CompassError(
            "omitting %r needs --reason. An omission with no reason is "
            "indistinguishable from a document nobody got to, and telling "
            "those apart is the whole point of recording it." % args.kind)

    entry["status"] = args.status
    if (args.reason or "").strip():
        entry["reason"] = args.reason.strip()
    task["artifacts"] = arts
    save_task(task, path)
    from compass_pkg.terminal import say

    return say(args, "compass issue artifact: %s -> %s" % (args.kind, args.status),
               detail=["reason: %s" % entry.get("reason", "(none recorded)"),
                       "regenerate the review page with `compass issue dashboard`"],
               kind=args.kind, status=args.status,
               reason=entry.get("reason"))
